<?php
	$title='Reuse - Adaptation Process';
	$this->headTitle($title);
?>

<div class="page-header">
    <h1><?php echo $this->escapeHTML($title); ?> </h1>
</div>
<div class="well">
 <p>
Based on relevant similarity with new case, SEECBR generate new solution effort estimation from last project in dataset. 
</p>
</div>
<p>
	<a class="btn btn-success btn-md" href='<?php echo $this->url('questioner'); ?>'><i class="fa fa-fw fa-angle-double-left"></i>Back to My Answer List</a>
</p>
<table class="table table-bordered table-hover table-striped">
	<tr>
		<th>Description</th>
		<th>Estimate</th>
	</tr>
<?php
	$arr=array();
	foreach($dataset as $arrDataset){
		
		foreach($arrDataset as $key=>$val){
			echo "<tr>";
			echo "<td>".$key."</td>";
			echo "<td>".$val."</td>";
			echo "</tr>";
		}
	}
?>
</table>
