<?php
	$cbrPart="Retain - ";
	$title=$cbrPart."Project Effort Estimation";
	$this->headTitle($title);	
?>

<div class="page-header">
    <h1><?php echo $this->escapeHTML($title); ?> </h1>
</div>

<?php
	
	if(isset($id_err)){
		?>
		 <div class="alert alert-warning">
              <strong>Warning!</strong> Best check yo self, <?php echo $err; ?> <a href='<?php echo $this->url('questioner'); ?>'>Go back</a>
         </div>
		<?php
	}
	
	if(isset($id_good)){
		?>
		 <div class="alert alert-success">
              <strong>Well done!</strong> Success, <?php echo $good; ?> <a href='<?php echo $this->url('questioner'); ?>'>Go back</a>
         </div>
		 
		 <div class="well">
		<p>
			Process Case Based Reasoning on effort estimation software has been complete. You can reuse record in dataset now.
		</p>
		</div>
		 
		<?php
	}

?>