<?php
	if($id_answer!=null){
		$cbrPart="Revise - ";
	}else{
		$cbrPart="";
	}
	$title=$cbrPart."Unadjusted Function Point Form";
	$this->headTitle($title);
?>
<div class="page-header">
    <h1><?php echo $this->escapeHTML($title); ?> </h1>
</div>
<div class="well">
 <p>
Fixed number given it would be counted by multiplication with weight component. Function points estimates are more accurate when performed by an experience developer.
</p>
</div>
<p>
<?php
	if($unadjustedFp!=null){
		?>
		<div class="alert alert-success">
           <strong>Well done!</strong> You successfully count Total Unadjusted Function Points(TUFP) = <?php echo $unadjustedFp; ?>
        </div>
		<?php
	}
?>
</p>
<p>
	<?php
	$form->setAttribute('action',$this->url('fpcalculation',array('action'=>'unadjustedfunctionpoint')));
	$form->prepare();
	echo $this->form()->openTag($form);
	echo $this->formHidden($form->get('id'));
	?>
	
	<table class="table">
		<tr>
			<th>Description</th>
			<th>Low</th>
			<th>Medium</th>
			<th>High</th>
		</tr>
		<?php
			$i=0;
			foreach($form->dataUnadjustedFPDesc as $desc){
				echo "<tr>";
				?>
				<td><?php echo $form->dataDescList[$i]; ?></td>
				<?php
				$j=0;
				foreach($form->dataUnadjustedFPCriteria as $cri){
					?>
					<td><div class="form-group input-group col-lg-6"> 
					<?php echo $this->formRow($form->get(''.$desc.'_'.$cri.'')); ?><span class="input-group-addon"><i class="fa fa-fw fa-times"></i><?php echo $form->dataMultiplication[$i][$j]; ?></span></div>
					</td>
					<?php
					$j++;
				}
				echo "</tr>";
				$i++;
			}
		?>
	</table>
	<input type='hidden' value='<?php echo $id_answer; ?>' name='id_answer'>
	<?php
	
	echo $this->formSubmit($form->get('submit'))." ".$this->formReset($form->get('reset'))."</br>";
	echo $this->form()->closeTag();
	?>
<p></p>

</p>
