<?php
	
	$title='My Answer Detail List';
	$this->headTitle($title);
	$aad=array();
?>

<h1>
	<?php echo $this->escapeHTML($title); ?> 
</h1>
<hr>
<p>
	<a class="btn btn-success btn-md" href='<?php echo $this->url('questioner'); ?>'><i class="fa fa-fw fa-angle-double-left"></i>Back to My Answer List</a>
</p>

<?php 
	foreach($question_detail as $quest):
		$aad[]=$quest->quest_data["question"];
	endforeach; 
?>

<table class="table">
	<tr>
		<th>ID</th>
		<th>Question</th>
		<th>Answer</th>
	</tr>
	<?php foreach($answer_detail as $key=>$answer):?>
		<tr>
			<td><?php echo $key+1; ?></td>
			<td><?php echo $aad[$key]."?"; ?></td>
			<td><?php 
			if($key==7){$answer.=" Month";}
			echo $answer; ?></td>
		</tr>
	<?php endforeach; ?>
</table>

<p>	<a class="btn btn-warning btn-md" href='<?php echo $this->url('estimate',array('action'=>'estimateProcess','id'=>$id)); ?>'>Go Estimate <i class="fa fa-fw fa-arrow-right"></i></a>
</p>