<?php
	$title="Info - About this site";
	$this->headTitle($title);
?>

<div class="page-header">
<h1>
	<?php echo $this->escapeHTML($title); ?>
</h1>
</div>

<div>
	<p>Software effort estimation plays an important role in software engineering. Thus, effort estimation usually be the determination of successful or failed in the negotiation contract as well as the determination of aggree or disaggree of the on going project.</p>
	<p>Today the software development has became a nessesary investment for every organisation. Therefore  <span class="zf-green"><b><i>SEE CBR</i></b></span> (<i>Software Effort Estimation Case Based Reasoning</i>) offer the contribution towards improvement of software engineering level.
	</p>
	<p>
	SEE CBR using <a href='http://www.cosmicon.com'>Cosmic</a>(<i>The Common Software Measurement International Consortium</i>) dataset with field contains ISBSG Rating Code of A and B. You can download dataset if you want to know a completely field. <a href='http://promisedata.googlecode.com/svn/trunk/effort/cosmic/cosmic.arff'>Download</a>
	</p>
	<p>
	Every work and effort when i was build the application it must be never complete without your aid. Please mail to <a href='mailto:edrianhadinata@gmail.com'>edrianhadinata@gmail.com</a> if you found an issue or bug.
	</p>
	<p>
	The last but not least i would like thanks to Sekolah Tinggi Teknik Harapan, through internal research of institution, SEE CBR adopt Case Based Reasoning methodology to improve this web application and make it come true.
	</p>
	<br>
	<p>
	Join and Try
	</p>
</div>